### ISSUE TITLE
set_on_parameters_set_callback is deprecated in Foxy

### ISSUE THREAD

**Issue by clydemcqueen** [ptrmu/ros2_shared#1]
I get these warnings in Foxy:

`warning: ‘rclcpp::Node::OnParametersSetCallbackType rclcpp::Node::set_on_parameters_set_callback(rclcpp::Node::OnParametersSetCallbackType)’ is deprecated: use add_on_set_parameters_callback(OnParametersSetCallbackType callback) instead [-Wdeprecated-declarations]`

As a workaround I've added this to my CMakeLists.txt file:

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-declarations")`

**Comment by ptrmu** [comment]
Fixed this. Your code needs to be modified to take advantage of the fix.
